export let FORM_INFO_PERSONA = {
    // titulo: 'InfoPersona',
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Guardar',
    modelo: 'InfoPersona',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'PrimerNombre',
            label_i18n: 'primer_nombre',
            placeholder_i18n: 'primer_nombre',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'SegundoNombre',
            label_i18n: 'segundo_nombre',
            placeholder_i18n: 'segundo_nombre',
            requerido: false,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'PrimerApellido',
            label_i18n: 'primer_apellido',
            placeholder_i18n: 'primer_apellido',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'SegundoApellido',
            label_i18n: 'segundo_apellido',
            placeholder_i18n: 'segundo_apellido',
            requerido: false,
            tipo: 'text',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'TipoIdentificacion',
            label_i18n: 'tipo_documento',
            placeholder_i18n: 'tipo_documento',
            requerido: true,
            tipo: 'TipoIdentificacion',
            key: 'Nombre',
            opciones: [ ],
        },
        {
            etiqueta: 'inputConfirmacion',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'NumeroIdentificacion',
            label_i18n: 'numero_documento',
            placeholder_i18n: 'numero_documento',
            requerido: true,
            mensajeIguales: 'Los datos no coinciden',
            tipo: 'number',
            minimo: 0,
            entrelazado: true,
        },
        {
            etiqueta: 'inputConfirmacion',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'VerificarNumeroIdentificacion',
            label_i18n: 'verificar_numero_documento',
            placeholder_i18n: 'verificar_numero_documento',
            requerido: true,
            tipo: 'number',
            minimo: 0,
            mensajeIguales: 'Los datos no coinciden',
            entrelazado: true,
        },
        {
            etiqueta: 'mat-date',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'FechaExpedicion',
            label_i18n: 'fecha_expedicion',
            placeholder_i18n: 'fecha_expedicion',
            requerido: true,
            tipo: 'date',
        },
        {
            etiqueta: 'mat-date',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'FechaNacimiento',
            label_i18n: 'fecha_nacimiento',
            placeholder_i18n: 'fecha_nacimiento',
            requerido: true,
            tipo: 'date',
        },     
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Genero',
            label_i18n: 'genero',
            placeholder_i18n: 'genero',
            requerido: true,
            tipo: 'Genero',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'EstadoCivil',
            label_i18n: 'estado_civil',
            placeholder_i18n: 'estado_civil',
            requerido: true,
            tipo: 'EstadoCivil',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'OrientacionSexual',
            label_i18n: 'orientacion_sexual',
            placeholder_i18n: 'orientacion_sexual',
            requerido: true,
            tipo: 'OrientacionSexual',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'IdentidadGenero',
            label_i18n: 'identidad_genero',
            placeholder_i18n: 'identidad_genero',
            requerido: true,
            tipo: 'IdentidadGenero',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'CorreoElectronico',
            label_i18n: 'correo_principal',
            placeholder_i18n: 'correo_principal',
            requerido: true,
            tipo: 'email',
            deshabilitar: true,
        },
        {
          etiqueta: 'input',
          claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
          nombre: 'Telefono',
          label_i18n: 'telefono',
          placeholder_i18n: 'telefono',
          requerido: true,
          tipo: 'number',
          minimo: 1000,
        },
    ],
}
