
export let FORM_DESCUENTO_PROYECTO = {
    titulo: 'Descuento',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    customPadding: '0',
    alertas: true,
    modelo: 'TipoDescuento',
    campos: [
      {
        etiqueta: 'input',
        claseGrid: '',
        nombre: 'Nombre',
        label_i18n: 'nombre',
        placeholder_i18n: 'nombre',
        requerido: true,
        tipo: 'text',
      },
      {
        etiqueta: 'input',
        claseGrid: '',
        nombre: 'Descripcion',
        label_i18n: 'descripcion',
        placeholder_i18n: 'descripcion',
        requerido: true,
        tipo: 'text',
      },
      {
        etiqueta: 'input',
        claseGrid: '',
        nombre: 'CodigoAbreviacion',
        label_i18n: 'codigo_abreviacion',
        placeholder_i18n: 'codigo_abreviacion',
        requerido: true,
        tipo: 'text',
      },
      {
        etiqueta: 'input',
        claseGrid: '',
        nombre: 'NumeroOrden',
        label_i18n: 'numero_orden',
        placeholder_i18n: 'numer_orden',
        requerido: true,
        tipo: 'number',
      },
      {
        etiqueta: 'input',
        claseGrid: '',
        nombre: 'ConceptoAcademicoId',
        label_i18n: 'concepto_academico_id',
        placeholder_i18n: 'concepto_academico_id',
        requerido: true,
        tipo: 'number',
      },
      {
        etiqueta: 'checkbox',
        claseGrid: '',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        valor: false,
      },
      {
        etiqueta: 'checkbox',
        claseGrid: '',
        nombre: 'General',
        label_i18n: 'general',
        placeholder_i18n: 'general',
        valor: false,
      },
    ],
  }